name: NoCK
version: 1.4
date: 2019-10-22
description: |
    NoCK-Package for computing obstruction for the existence of compact Clifford-Klein form.

authors:
    - name: Maciej Bocheński
      url: mailto:mabo@matman.uwm.edu.pl
    - name: Piotr Jastrzębski
      url: http://wmii.uwm.edu.pl/~piojas/
    - name: Anna Szczepkowska
      url: mailto:anna.szczepkowska@matman.uwm.edu.pl
    - name: Aleksy Tralle
      url: http://wmii.uwm.edu.pl/~tralle/
    - name: Artur Woike
      url: http://wmii.uwm.edu.pl/~awoike

maintainers:
    - name: Maciej Bocheński
      url: mailto:mabo@matman.uwm.edu.pl
    - name: Piotr Jastrzębski
      url: http://wmii.uwm.edu.pl/~piojas/
    - name: Anna Szczepkowska
      url: mailto:anna.szczepkowska@matman.uwm.edu.pl
    - name: Aleksy Tralle
      url: http://wmii.uwm.edu.pl/~tralle/
    - name: Artur Woike
      url: http://wmii.uwm.edu.pl/~awoike

GAP: ">=4.8"

needed-pkgs:
    - name: "sla"
      version: ">=1.2"
    - name: "CoReLG"
      version: ">=1.20"

suggested-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://pjastr.github.io/NoCK
readme: README.md
packageinfo: https://pjastr.github.io/NoCK/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/pjastr/NoCK/releases/download/v1.4/NoCK-1.4.tar.gz

abstract: |
    The <span class="pkgname">NoCK</span> package    is used for computitation Tolzanos's obstruction    for compact Clifford-Klein forms

status: submitted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
